CREATE TABLE TRANSACTIONS
  (
    TRANSACTIONID          VARCHAR2 (10 BYTE)  PRIMARY KEY NOT NULL ,
    ORDERID                VARCHAR2 (10 BYTE) ,
    PRICEID                VARCHAR2 (10 BYTE) ,
    TRANSACTIONDATE        DATE ,
    TRANSACTIONDESCRIPTION VARCHAR2 (30 BYTE) ,
    TRANSACTIONAMOUNT      NUMBER (20) ,
    EMPLOYEEID             VARCHAR2 (10 BYTE) ,
    TRUCKID                VARCHAR2 (2 BYTE) ,
    DISCOUNT               NUMBER (20) ,
    QUANTITY               NUMBER (10) ,
    UNITPRICE              NUMBER (30) ,
    DRIVERPRICE            NUMBER (20) ,
    RUNNUMBER              VARCHAR2 (2 BYTE) ,
    SPECIAL                VARCHAR2 (20 BYTE) ,
    RATE                   NUMBER (10) ,
    SURCHARGE              NUMBER (10)
  )
  
  CREATE TABLE PRICING
  (
    PRICEID          VARCHAR2 (20 BYTE)  PRIMARY KEY NOT NULL ,
    LOCATIONIDFROM   VARCHAR2 (20 BYTE) ,
    LOCATIONIDTO     VARCHAR2 (20 BYTE) ,
    PRICE            NUMBER (20) ,
    LOCATIONCODEFROM VARCHAR2 (10 BYTE) ,
    LOCATIONCODETO   VARCHAR2 (10 BYTE) ,
    LOCATIONNAMEFROM VARCHAR2 (20 BYTE) ,
    LOCATIONNAMETO   VARCHAR2 (20 BYTE) ,
    CUSTOMERID       VARCHAR2 (10 BYTE)
  )
  
  CREATE TABLE EMPLOYEES
  (
    EMPLOYEEID          VARCHAR2 (10 BYTE)  PRIMARY KEY NOT NULL ,
    FIRSTNAME           VARCHAR2 (10 BYTE) ,
    LASTNAME            VARCHAR2 (10 BYTE) ,
    EMAIL               VARCHAR2 (30 BYTE) ,
    EXTENSION           VARCHAR2 (10 BYTE) ,
    HOMEPHONE           NUMBER (10) ,
    CELLPHONE           NUMBER (10) ,
    JOB_TITLE           VARCHAR2 (10 BYTE) ,
    SSN                 NUMBER (9) ,
    DRIVERLICENCENUMBER VARCHAR2 (9 BYTE) ,
    ADDRESS             VARCHAR2 (30 BYTE) ,
    CITY                VARCHAR2 (10 BYTE) ,
    STATE               VARCHAR2 (10 BYTE) ,
    POSTALCODE          NUMBER (5) ,
    BIRTHDATE           DATE ,
    DATEHIRED           DATE ,
    SALARY              NUMBER (20) ,
    NOTES               VARCHAR2 (50 BYTE)
  )
  
  CREATE TABLE ORDERS
  (
    ORDERID             VARCHAR2 (10 BYTE)  PRIMARY KEY NOT NULL ,
    ORDERDATE           DATE ,
    CUSTOMERID          VARCHAR2 (10 BYTE) ,
    EMPLOYEEID          VARCHAR2 (10 BYTE) ,
    TRUCKID             VARCHAR2 (10 BYTE) ,
    PURCHASEORDERNUMBER VARCHAR2 (10 BYTE) ,
    ORDERTOTALAMOUNT    NUMBER (30) ,
    ISSPECIAL           VARCHAR2 (10 BYTE)
  )
  
  CREATE TABLE PAYMENTS
  (
    PAYMENTID                     VARCHAR2 (10 BYTE)  PRIMARY KEY NOT NULL ,
    ORDERID                       VARCHAR2 (10 BYTE) ,
    PAYMENTMETHOD                 VARCHAR2 (10 BYTE) ,
    PAYMENTAMOUNT                 NUMBER (10) ,
    PAYMENTDATE                   DATE ,
    CHECKNUMBER                   VARCHAR2 (20 BYTE) ,
    CREDITCARDTYPE                VARCHAR2 (10 BYTE) ,
    CREDITCARDNUMBER              NUMBER (25) ,
    CARDHOLDERSNAME               VARCHAR2 (20 BYTE) ,
    CREDITCARDEXPDATE             DATE ,
    CREDITCARDAUTHORIZATIONNUMBER NUMBER (3)
  )
  
    CREATE TABLE EXPENSES
  (
    EXPENSEID        VARCHAR2 (10 BYTE)  PRIMARY KEY NOT NULL ,
    EMPLOYEEID       VARCHAR2 (10 BYTE) ,
    TRUCKID          VARCHAR2 (10 BYTE) ,
    EXPENSETYPE      VARCHAR2 (10 BYTE) ,
    PURPOSEOFEXPENSE VARCHAR2 (20 BYTE) ,
    AMOUNTSPENT      NUMBER (20) ,
    DESCRIPTION      VARCHAR2 (30 BYTE) ,
    DATEPURCHASED    DATE ,
    DATESUBMITTED    DATE ,
    ADVANCEAMOUNT    NUMBER (20) ,
    PAYMENTMETHOD    VARCHAR2 (10 BYTE)
  )
  
  CREATE TABLE CUSTOMERS
  (
    CUSTOMERID           VARCHAR2 (10 BYTE)  PRIMARY KEY NOT NULL ,
    CUSTOMERTITLE        VARCHAR2 (20 BYTE) ,
    BUSINESSNAME         VARCHAR2 (20 BYTE) ,
    BILLINGADDRESS       VARCHAR2 (30 BYTE) ,
    CITY                 VARCHAR2 (10 BYTE) ,
    STATEORPROVINCE      VARCHAR2 (10 BYTE) ,
    POSTALCODE           NUMBER (5) ,
    COUNTRY              VARCHAR2 (10 BYTE) ,
    PHONENUMBER          NUMBER (10) ,
    CELLNUMBER           NUMBER (10) ,
    OTHERNUMBER          NUMBER (10) ,
    FAXNUMBER            NUMBER (10) ,
    EMAILADDRESS         VARCHAR2 (20 BYTE) ,
    CUSTOMER_type        VARCHAR2 (20 BYTE) ,
    COMPANYNAME          VARCHAR2 (10 BYTE) ,
    CONTACTNAME          VARCHAR2 (20 BYTE) ,
    ALTERNATECONTACTNAME VARCHAR2 (20 BYTE) ,
    DATEENTERED          DATE
  )
  
  CREATE TABLE COMMENTS
  (
    COMMENTSID   VARCHAR2 (10 BYTE)  PRIMARY KEY NOT NULL ,
    COMMENTS     VARCHAR2 (100 BYTE) ,
    COMMENTSTYPE VARCHAR2 (10 BYTE) ,
    CUSTOMERID   VARCHAR2 (10 BYTE)
  )
  
  CREATE TABLE TRUCKS
  (
    TRUCKID        VARCHAR2 (20 BYTE)  PRIMARY KEY NOT NULL ,
    MAKE           VARCHAR2 (20 BYTE) ,
    YEAR           NUMBER (4) ,
    MODEL          VARCHAR2 (20 BYTE) ,
    LICENCEPLATENO VARCHAR2 (20 BYTE) ,
    COLOR          VARCHAR2 (10 BYTE) ,
    VIN            VARCHAR2 (17 BYTE) ,
    DRIVERID       VARCHAR2 (20 BYTE)
  )
  
  
  CREATE TABLE LOCATIONS
  (
    LOCATIONID            VARCHAR2 (10 BYTE)  PRIMARY KEY NOT NULL ,
    LOCNAME               VARCHAR2 (10 BYTE) ,
    LOCATIONCODE          VARCHAR2 (10 BYTE) ,
    ISAUCTION             VARCHAR2 (10 BYTE) ,
    CUSTOMERID            VARCHAR2 (10 BYTE) ,
    ADDRESS_STREET1       VARCHAR2 (20 BYTE) ,
    ADDRESS_STREET2       VARCHAR2 (20 BYTE) ,
    CITY                  VARCHAR2 (10 BYTE) ,
    STATE                 VARCHAR2 (10 BYTE) ,
    POSTALCODE            NUMBER (5) ,
    REGION                VARCHAR2 (10 BYTE) ,
    LOCATION_CONTACT_NAME VARCHAR2 (20 BYTE) ,
    LOCPHONE              NUMBER (10) ,
    LOCFAXNUMBER          NUMBER (10) ,
    LOCEMAIL              VARCHAR2 (10 BYTE)
  )
  
  CREATE TABLE INVOICES
  (
    INVOICEID            VARCHAR2 (10 BYTE)  PRIMARY KEY NOT NULL ,
    ORDERID               VARCHAR2 (10 BYTE) ,
    CUSTOMERID          VARCHAR2 (10 BYTE) ,
    PAYMENTID             VARCHAR2 (10 BYTE) ,
    PRICEID            VARCHAR2 (10 BYTE) ,
    TRANSACTIONID       VARCHAR2 (20 BYTE) ,
    TRUCKID     		VARCHAR2 (20 BYTE) ,
    EXPENSEID                  VARCHAR2 (10 BYTE) ,
  )